### ISSUE TITLE
Output to File

### ISSUE THREAD

**Issue by csalazar1** [travisjeffery/mocha-teamcity-reporter#60]
Is there no way to output results to file? I didn't see any under the options listed

**Comment by DJ-Glock** [comment]
@csalazar1 I can also recommend using `| tee e2e.log`. You can check my response [here](https://stackoverflow.com/questions/11354203/is-it-possible-to-get-the-raw-build-log-from-a-teamcity-build/67635511#67635511).

`tee` will duplicate output into the file without harming the original output that is parsed by TeamCity.

**Comment by csalazar1** [comment]
Thank you for the response guys! The use case is actually for someone that wants to have multiple reporters. In this case, the first reporter would be outputting to STDOUT and the second reporter, mocha-teamcity, should be outputting to log file.

**Comment by DJ-Glock** [comment]
@csalazar1 in case if you want to have a several reporters, I would recommend you use https://github.com/stanleyhlng/mocha-multi-reporters. I had some experiments with this lib and another similar one, but found it much more useful. I think about using it even with one reporter because it allows to configure reporter options easier than several parameters in one line (i use CLI command for running tests).

I just faced one issue when was configuring mocha-teamcity-reporter in mocha-multi-reporters - passing boolean value to report parameter. If I remember correctly, boolean value should be double quoted, like this: "true".

Both reporters will output in the same place and should not hurt each other because you will use different reporters I believe.

**Comment by jamie-sherriff** [comment]
I have updated the readme with some of the highlights from this issue but if there is anything else to add please reopen with a comment.
